export const mockTransactions = [
  {
    id: "txn_001",
    type: "credit",
    amount: 50000,
    date: "2023-06-15T09:30:00",
    title: "Salary Deposit",
    description: "Monthly salary from company",
    status: "successful",
    reference: "SAL-0623-001",
    from: "ABC Corporation",
    to: "My Wallet",
    category: "income"
  },
  {
    id: "txn_002",
    type: "debit",
    amount: 15000,
    date: "2023-06-15T11:45:00",
    title: "Rent Payment",
    description: "Monthly apartment rent",
    status: "successful",
    reference: "RENT-0623",
    from: "My Wallet",
    to: "Landlord Ltd",
    category: "housing"
  },
  {
    id: "txn_003",
    type: "debit",
    amount: 3500,
    date: "2023-06-16T14:20:00",
    title: "Grocery Shopping",
    description: "Supermarket purchase",
    status: "successful",
    reference: "POS-987654",
    from: "My Wallet",
    to: "SuperMart NG",
    category: "shopping"
  },
  {
    id: "txn_004",
    type: "credit",
    amount: 25000,
    date: "2023-06-17T16:10:00",
    title: "Freelance Payment",
    description: "Website development project",
    status: "successful",
    reference: "FL-0623-001",
    from: "Client Inc",
    to: "My Wallet",
    category: "income"
  },
  {
    id: "txn_005",
    type: "debit",
    amount: 5000,
    date: "2023-06-18T19:05:00",
    title: "Dinner Out",
    description: "Restaurant bill",
    status: "successful",
    reference: "POS-123456",
    from: "My Wallet",
    to: "Food Haven",
    category: "food"
  },
  {
    id: "txn_006",
    type: "credit",
    amount: 10000,
    date: "2023-06-19T10:15:00",
    title: "Bank Transfer",
    description: "From friend",
    status: "pending",
    reference: "TRF-987321",
    from: "John Doe",
    to: "My Wallet",
    category: "transfer"
  },
  {
    id: "txn_007",
    type: "debit",
    amount: 2000,
    date: "2023-06-20T07:30:00",
    title: "Airtime Purchase",
    description: "MTN airtime",
    status: "successful",
    reference: "AIRT-456789",
    from: "My Wallet",
    to: "MTN Nigeria",
    category: "utilities"
  },
  {
    id: "txn_008",
    type: "debit",
    amount: 12000,
    date: "2023-06-21T13:25:00",
    title: "Electricity Bill",
    description: "IKEDC payment",
    status: "failed",
    reference: "IKEDC-789012",
    from: "My Wallet",
    to: "IKEDC",
    category: "utilities",
    failureReason: "Insufficient balance"
  },
  {
    id: "txn_009",
    type: "credit",
    amount: 7500,
    date: "2023-06-22T15:40:00",
    title: "Refund",
    description: "Online store return",
    status: "successful",
    reference: "RFND-654321",
    from: "ShopOnline NG",
    to: "My Wallet",
    category: "shopping"
  },
  {
    id: "txn_010",
    type: "debit",
    amount: 3000,
    date: "2023-06-23T08:15:00",
    title: "Transport",
    description: "Uber ride",
    status: "successful",
    reference: "UBER-321654",
    from: "My Wallet",
    to: "Uber Nigeria",
    category: "transport"
  }
];